cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_BUCKET_NAME}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false